import './all.css';
import './all.min.css';
import './brands.css';
import './brands.min.css';
import './fontawesome.css ';
import './fontawesome.min.css ';
import './regular.css ';
import './regular.min.css ';
import './solid.css ';
import './solid.min.css ';
import './svg-with-js.css ';
import './svg-with-js.min.css ';
import './v4-shims.css ';
import './v4-shims.min.css ';
